services:

  db:
    image: postgres:16
    container_name: login_postgres
    restart: always

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build: ./backend
    container_name: login_backend

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: ${DATABASE_URL}

    depends_on:
      - db


  frontend:
    build: ./frontend
    container_name: login_frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend


volumes:
  postgres_data: